

#  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Nzg1ZDg5YzliZGZjMGVhYjQzNjZkYiIsImlhdCI6MTc2OTQ5NTk0NX0.caTZ6WrOaCIcxYnim-H0JsY7t-8NjGEyl1DylRhm-u4"
# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email":"naune@hotmail.com",
#     "password":"vakeeL@234"
# }



POST http://localhost:3000/user-written-blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTQwOTQzNThlZTcwZDk0OGQyZTg3NiIsImlhdCI6MTc3MTgyNjMzNn0.d38rXvw9lyKt0evJLRR3yIVii9paG99j46KLkeoktww
Content-Type: application/json 

{
    "page":1,
    "draft":false
}
